// Generated by scripts/logo/gen.py — do not edit. viewBox width / height per logo file.
export const LOGO_ASPECT = {
  full: { ar: 3.0168, en: 3.7693 },
  wordmark: { ar: 3.3284, en: 3.0365 },
} as const;
