"""Builds the Sada brand book (rule 08) into docs/brand/. Never hand-edit the output.

Run: python3 scripts/brand/build.py            # HTML + AR/EN PDFs (needs Google Chrome)
     python3 scripts/brand/build.py --no-pdf   # HTML only
Override Chrome path with CHROME=/path/to/chrome.

template.html placeholders:
  /*{{FONTS}}*/     Tajawal @font-face rules, base64 from scripts/brand/fonts/
  {{logo:<name>}}   inline SVG from src/assets/images/logo/<name>.svg (generated by scripts/logo/gen.py)
  {{v:<name>}}      lockup measurements read from logo-full-light.svg
"""
import base64, os, pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
LOGO = ROOT / 'src' / 'assets' / 'images' / 'logo'
OUT = ROOT / 'docs' / 'brand'
CHROME = os.environ.get('CHROME', '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')
WEIGHTS = {'Light': 300, 'Regular': 400, 'Medium': 500, 'Bold': 700, 'ExtraBold': 800}


def fonts():
    rules = []
    for name, weight in WEIGHTS.items():
        data = base64.b64encode((HERE / 'fonts' / f'Tajawal-{name}.ttf').read_bytes()).decode()
        rules.append(f"@font-face{{font-family:Tajawal;font-weight:{weight};font-display:block;"
                     f"src:url(data:font/ttf;base64,{data}) format('truetype')}}")
    return '\n'.join(rules)


def logo(name):
    return (LOGO / f'{name}.svg').read_text().strip()


def measures():
    s = logo('logo-full-light')
    w, h = map(float, re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', s).groups())
    cx, cy = re.search(r'<circle cx="([\d.]+)" cy="([\d.]+)" r="5"', s).groups()
    sx = w - 120
    return {'w': f'{w:.2f}', 'h': f'{h:.2f}', 'sx': f'{sx:.2f}', 'ww': f'{sx - 23:.2f}', 'dotx': cx, 'doty': cy}


html = (HERE / 'template.html').read_text()
html = html.replace('/*{{FONTS}}*/', fonts())
html = re.sub(r'\{\{logo:([\w-]+)\}\}', lambda m: logo(m.group(1)), html)
v = measures()
html = re.sub(r'\{\{v:(\w+)\}\}', lambda m: v[m.group(1)], html)
assert '{{' not in html, 'unresolved placeholder'

OUT.mkdir(parents=True, exist_ok=True)
page = OUT / 'sada-brand-book.html'
page.write_text(html)
print(page.relative_to(ROOT), len(html))

if '--no-pdf' not in sys.argv:
    for lang in ('ar', 'en'):
        pdf = OUT / f'sada-brand-book-{lang}.pdf'
        subprocess.run([CHROME, '--headless=new', '--disable-gpu', '--no-pdf-header-footer',
                        '--virtual-time-budget=8000', f'--print-to-pdf={pdf}',
                        f'{page.as_uri()}?lang={lang}&print=1'], check=True, capture_output=True)
        print(pdf.relative_to(ROOT), pdf.stat().st_size)
